#!/bin/bash
#
#  Usage:
#	(cd ../src && make clean hoq)
#	./regress
#
set -x
(cd ../src && make clean hoq) || exit

export LANG=C
PATH=.:../src/$PATH

seq 1000 | hoq regress.hoq | sort | shasum
cat regress.sha1
