#!/bin/bash
#
#  Synopsis:
#	Very trivial regression test
#  Usage:
#	./regress
#  Note:
#	Still not clear if LC_ALL overrides all other LC_* variables.
#
#	     http://unix.stackexchange.com/questions/87745/what-does-lc-all-c-do
#
#	The command shasum may not exist in some unix distros,  like 2.8.18
#	redhat.
#
SEQ_LIMIT=1000
set -x
rm -f regress.out
(cd ../src && make clean hoq) || exit

#  unset an locale environment variables

unset $(locale | cut -d = -f1)

#  reset to all LC vars to C.
#
#  Note: should the unset LC vars in previous staement be set to C? 

export LC_ALL=C

PATH=.:../src:$PATH

seq $SEQ_LIMIT | perl -MList::Util=shuffle -e 'print shuffle(<STDIN>);' | time hoq regress.hoq | sort | tee regress.out | shasum
cat regress.sha1
