#!/usr/bin/env perl
#
#  Synopsis:
#	Implements argument processing for /cgi-bin/daily.
#  Source Path:
#	daily.cgi
#  Source SHA1 Digest:
#	No SHA1 Calculated
#  Note:
#	/cgi-bin/daily was generated automatically by cgi2perl5.
#
#	Do not make changes directly to this script.
#
die "SERVER_ROOT environment variable not defined"
				unless defined $ENV{SERVER_ROOT};

#
#  Prepend the $SERVER_ROOT/lib directory
#  to the load path.
#
unshift @INC, "$ENV{SERVER_ROOT}/lib";

our (%CGI);

require 'httpd2.d/common.pl';
$CGI{name} = 'daily';

#
#  BEGIN: /cgi/GET/out/query-args
#
$CGI{GET}->{out}->{'query-args'}->{arg}->{id} = {
	perl5_re	=>	'\w[\w-]{0,32}'
};
$CGI{GET}->{out}->{'query-args'}->{arg}->{class} = {
	perl5_re	=>	'\w[\w-]{0,32}'
};
#
#  'out' query argument must match one of the out putter names.
#
$CGI{GET}->{out}->{'query-args'}->{arg}->{out} = {
	perl5_re	=> 	'dl|(?:span[.]nav)|text|(?:mime[.]tar)|help',
	default		=>	'help',
};
#
#  BEGIN: /cgi/GET/out/putter[@name='dl']
#
$CGI{GET}->{out}->{putter}->{'dl'}->{name} = 'dl';
$CGI{GET}->{out}->{putter}->{'dl'}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/putter[@name=dl]/query-args
#
$CGI{GET}->{out}->{putter}->{'dl'}->{'query-args'}->{arg}->{lim} = {
	perl5_re	=>	'10|100',
	default	=>	'10',
	required	=>	'no',
};
$CGI{GET}->{out}->{putter}->{'dl'}->{'query-args'}->{arg}->{off} = {
	perl5_re	=>	'[0-9]{1,4}',
};
#
#  END: /cgi/GET/out/putter[@name=dl]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='dl']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='span.nav']
#
$CGI{GET}->{out}->{putter}->{'span.nav'}->{name} = 'span.nav';
$CGI{GET}->{out}->{putter}->{'span.nav'}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/putter[@name=span.nav]/query-args
#
$CGI{GET}->{out}->{putter}->{'span.nav'}->{'query-args'}->{arg}->{lim} = {
	perl5_re	=>	'10|100',
	default	=>	'10',
	required	=>	'no',
};
$CGI{GET}->{out}->{putter}->{'span.nav'}->{'query-args'}->{arg}->{off} = {
	perl5_re	=>	'[0-9]{1,4}',
};
#
#  END: /cgi/GET/out/putter[@name=span.nav]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='span.nav']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='text']
#
$CGI{GET}->{out}->{putter}->{'text'}->{name} = 'text';
$CGI{GET}->{out}->{putter}->{'text'}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/putter[@name=text]/query-args
#
#
#  END: /cgi/GET/out/putter[@name='text']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='mime.tar']
#
$CGI{GET}->{out}->{putter}->{'mime.tar'}->{name} = 'mime.tar';

#
#  BEGIN: /cgi/GET/out/putter[@name=mime.tar]/query-args
#
$CGI{GET}->{out}->{putter}->{'mime.tar'}->{'query-args'}->{arg}->{blob} = {
	perl5_re	=>	'[a-z][a-z0-9]{0,7}:[[:graph:]]{32,128}',
	required	=>	'yes',
};
#
#  END: /cgi/GET/out/putter[@name=mime.tar]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='mime.tar']
#

$CGI{GET}->{out}->{putter}->{help}->{name} = 'help';
$CGI{GET}->{out}->{putter}->{help}->{'content-type'} = 'text/html';

require "httpd2.d/$ENV{REQUEST_METHOD}.pl";
