// Code generated by goyacc -o parser.go parser.y. DO NOT EDIT.

//line parser.y:12
package main

import __yyfmt__ "fmt"

//line parser.y:12

import (
	"bufio"
	"errors"
	"fmt"
	"io"
	"os"
	"strconv"
	"unicode"
)

const max_name_rune_count = 127

func init() {

	if yyToknames[3] != "__MIN_YYTOK" {
		panic("yyToknames[3] != __MIN_YYTOK: correct yacc command?")
	}
	//yyDebug = 4
}

//line parser.y:35
type yySymType struct {
	yys    int
	ast    *ast
	name   string
	string string
	uint64 uint64
	int
}

const __MIN_YYTOK = 57346
const PARSE_ERROR = 57347
const ARG = 57348
const ARG_LIST = 57349
const ATT = 57350
const ATT_TUPLE = 57351
const ATT_ARRAY = 57352
const RUN = 57353
const COMMAND = 57354
const COMMAND_REF = 57355
const CREATE = 57356
const EXPAND_ENV = 57357
const FLOW = 57358
const STMT = 57359
const NAME = 57360
const UINT64 = 57361
const STRING = 57362
const OF = 57363
const LINES = 57364
const SCANNER = 57365
const SCANNER_REF = 57366
const TRACER = 57367
const TRACER_REF = 57368
const yy_TRUE = 57369
const yy_FALSE = 57370
const yy_AND = 57371
const yy_OR = 57372
const NOT = 57373
const EQ = 57374
const NEQ = 57375
const GT = 57376
const GTE = 57377
const LT = 57378
const LTE = 57379
const MATCH = 57380
const NO_MATCH = 57381
const CONCAT = 57382
const WHEN = 57383

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"__MIN_YYTOK",
	"PARSE_ERROR",
	"ARG",
	"ARG_LIST",
	"ATT",
	"ATT_TUPLE",
	"ATT_ARRAY",
	"RUN",
	"COMMAND",
	"COMMAND_REF",
	"CREATE",
	"EXPAND_ENV",
	"FLOW",
	"STMT",
	"NAME",
	"UINT64",
	"STRING",
	"OF",
	"LINES",
	"SCANNER",
	"SCANNER_REF",
	"TRACER",
	"TRACER_REF",
	"yy_TRUE",
	"yy_FALSE",
	"yy_AND",
	"yy_OR",
	"NOT",
	"EQ",
	"NEQ",
	"GT",
	"GTE",
	"LT",
	"LTE",
	"MATCH",
	"NO_MATCH",
	"CONCAT",
	"WHEN",
	"','",
	"'['",
	"']'",
	"':'",
	"'{'",
	"'}'",
	"'('",
	"')'",
	"';'",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line parser.y:710

var keyword = map[string]int{
	"and":       yy_AND,
	"Command":   COMMAND,
	"create":    CREATE,
	"ExpandEnv": EXPAND_ENV,
	"false":     yy_FALSE,
	"lines":     LINES,
	"not":       NOT,
	"of":        OF,
	"or":        yy_OR,
	"run":       RUN,
	"Scanner":   SCANNER,
	"Tracer":    TRACER,
	"true":      yy_TRUE,
	"when":      WHEN,
}

type yyLexState struct {
	in      io.RuneReader //  source stream
	line_no int           //  lexical line number
	eof     bool          //  seen eof in token stream
	peek    rune          //  lookahead in lexer
	err     error

	ast_root *ast
	name     string
	string
	uint64

	name2ast     map[string]*ast
	run_cmd2ast  map[*command]*ast
	name_is_name bool
}

func (lex *yyLexState) pushback(c rune) {

	if lex.peek != 0 {
		panic("pushback(): push before peek") /* impossible */
	}
	lex.peek = c
	if c == '\n' {
		lex.line_no--
	}
}

/*
 *  Read next UTF8 rune.
 */
func (lex *yyLexState) get() (c rune, eof bool, err error) {

	if lex.eof {
		return 0, true, nil
	}
	if lex.peek != 0 { /* returned stashed char */
		c = lex.peek
		/*
		 *  Only pushback 1 char.
		 */
		lex.peek = 0
		if c == '\n' {
			lex.line_no++
		}
		return c, false, nil
	}
	c, _, err = lex.in.ReadRune()
	if err != nil {
		if err == io.EOF {
			lex.eof = true
			return 0, true, nil
		}
		return 0, false, err
	}

	if c == unicode.ReplacementChar {
		return 0, false, lex.mkerror("get: invalid unicode sequence")
	}
	if c == '\n' {
		lex.line_no++
	}
	return c, false, nil
}

func (lex *yyLexState) lookahead(peek rune, ifyes int, ifno int) (int, error) {

	next, eof, err := lex.get()
	if err != nil {
		return 0, err
	}
	if next == peek {
		return ifyes, err
	}
	if !eof {
		lex.pushback(next)
	}
	return ifno, nil
}

/*
 *  Skip '#' comment.
 *  The scan stops on the terminating newline or error
 */
func skip_comment(lex *yyLexState) (err error) {
	var c rune
	var eof bool

	/*
	 *  Scan for newline, end of file, or error.
	 */
	for c, eof, err = lex.get(); !eof && err == nil; c, eof, err = lex.get() {
		if c == '\n' {
			return
		}
	}
	return err

}

// skip over whitespace in code, complicated by # coments.

func skip_space(lex *yyLexState) (c rune, eof bool, err error) {

	for c, eof, err = lex.get(); !eof && err == nil; c, eof, err = lex.get() {
		if unicode.IsSpace(c) {
			continue
		}
		if c != '#' {
			return c, false, nil
		}

		/*
		 *  Skipping over # comment terminated by newline or EOF
		 */
		err = skip_comment(lex)
		if err != nil {
			return 0, false, err
		}
	}
	return 0, eof, err
}

/*
 *  Very simple utf8 string scanning, with no proper escapes for characters.
 *  Expect this module to be replaced with correct text.Scanner.
 */
func (lex *yyLexState) scanner_string(yylval *yySymType) (eof bool, err error) {
	var c rune
	s := ""

	for c, eof, err = lex.get(); !eof && err == nil; c, eof, err = lex.get() {
		if c == '"' {
			yylval.string = s
			return false, nil
		}
		switch c {
		case '\n':
			return false, lex.mkerror("new line in string")
		case '\r':
			return false, lex.mkerror("carriage return in string")
		case '\t':
			return false, lex.mkerror("tab in string")
		case '\\':
			return false, lex.mkerror("backslash in string")
		}
		s += string(c)
	}
	if err != nil {
		return false, err
	}
	return true, nil
}

/*
 *  Scan an almost raw `...`  string as defined in golang.
 *  Carriage return is stripped.
 */
func (lex *yyLexState) scanner_raw_string(yylval *yySymType) (eof bool, err error) {
	var c rune
	s := ""

	/*
	 *  Scan a raw string of unicode letters, accepting all but `
	 */
	for c, eof, err = lex.get(); !eof && err == nil; c, eof, err = lex.get() {

		switch c {
		case '\r':
			//  why does go skip carriage return?  raw is not so raw
			continue
		case '`':
			yylval.string = s
			return false, nil
		}
		s += string(c)
	}
	if err != nil {
		return false, err
	}
	return true, nil
}

/*
 *  Scan a word consisting of a sequence of unicode Letters, Numbers and '_'
 *  characters.
 */
func (lex *yyLexState) scanner_word(
	yylval *yySymType,
	c rune,
) (tok int, err error) {
	var eof bool

	w := string(c) //  panic() if cast fails?
	count := 1

	/*
	 *  Scan a string of unicode (?) letters, numbers/digits and '_'
	 *  characters.
	 */
	for c, eof, err = lex.get(); !eof && err == nil; c, eof, err = lex.get() {
		if c > 127 ||
			(c != '_' &&
				!unicode.IsLetter(c) &&
				!unicode.IsNumber(c)) {
			break
		}
		count++
		if count > max_name_rune_count {
			return 0, lex.mkerror("word: too many chars: max=%d",
				max_name_rune_count)
		}
		w += string(c) //  Note: replace with string builder?
	}
	if err != nil {
		return 0, err
	}
	if !eof {
		lex.pushback(c) /* first character after word */
	}

	if keyword[w] > 0 { /* got a keyword */
		return keyword[w], nil /* return yacc generated token */
	}

	lex.name = w
	if lex.name_is_name == false && lex.name2ast[w] != nil {
		yylval.name = w
		return lex.name2ast[w].yy_tok, nil
	}
	return NAME, nil
}

func (lex *yyLexState) scanner_uint64(yylval *yySymType, c rune) (err error) {
	var eof bool

	ui64 := string(c)
	count := 1

	/*
	 *  Scan a string of unicode numbers/digits and let Scanf parse the
	 *  actual digit string.
	 */
	for c, eof, err = lex.get(); !eof && err == nil; c, eof, err = lex.get() {
		count++
		if count > 20 {
			return lex.mkerror("uint64 > 20 digits")
		}
		if c > 127 || !unicode.IsNumber(c) {
			break
		}
		ui64 += string(c)
	}
	if err != nil {
		return
	}
	if !eof {
		lex.pushback(c) //  first character after ui64
	}

	yylval.uint64, err = strconv.ParseUint(ui64, 10, 64)
	return
}

//  lexical scan of a token

func (lex *yyLexState) Lex(yylval *yySymType) (tok int) {

	if lex.err != nil {
		return PARSE_ERROR
	}
	if lex.eof {
		return 0
	}
	c, eof, err := skip_space(lex)
	if err != nil {
		goto LEX_ERROR
	}
	if eof {
		return 0
	}

	switch {

	//  ascii outside of strings, for time being (why?)
	case c > 127:
		err = lex.mkerror("char not ascii: 0x%x", c)
		goto LEX_ERROR

	case c == '=':
		//  clang "==" equality

		tok, err = lex.lookahead('=', EQ, 0)
		if err != nil {
			goto LEX_ERROR
		}
		if tok != 0 {
			return tok
		}

		//  expr regexp operator "=~"

		tok, err = lex.lookahead('~', MATCH, 0)
		if err != nil {
			goto LEX_ERROR
		}
		return tok

	case c == '!':
		//  clang inequality "!="

		tok, err = lex.lookahead('=', NEQ, 0)
		if err != nil {
			goto LEX_ERROR
		}
		if tok != 0 {
			return tok
		}

		//  expr negate match regexp operator "!~"

		tok, err = lex.lookahead('~', NO_MATCH, 0)
		if err != nil {
			goto LEX_ERROR
		}
		return tok

	case c == '|':
		tok, err = lex.lookahead('|', CONCAT, '|')
		if err != nil {
			goto LEX_ERROR
		}
		return tok

	case c == '>':
		tok, err = lex.lookahead('=', GTE, GT)
		if err != nil {
			goto LEX_ERROR
		}
		return tok

	case c == '<':

		tok, err = lex.lookahead('=', LTE, LT)
		if err != nil {
			goto LEX_ERROR
		}
		return tok

	case unicode.IsLetter(c) || c == '_':
		tok, err = lex.scanner_word(yylval, c)
		if err != nil {
			goto LEX_ERROR
		}
		return tok

	case unicode.IsNumber(c):
		err = lex.scanner_uint64(yylval, c)
		if err != nil {
			goto LEX_ERROR
		}
		return UINT64

	case c == '"':
		lno := lex.line_no // reset line number on error

		eof, err = lex.scanner_string(yylval)
		if err != nil {
			goto LEX_ERROR
		}
		if eof {
			lex.line_no = lno
			err = lex.mkerror("unexpected end of file in string")
			goto LEX_ERROR
		}
		return STRING

	case c == '`':
		lno := lex.line_no // reset line number on error

		eof, err = lex.scanner_raw_string(yylval)
		if err != nil {
			goto LEX_ERROR
		}
		if eof {
			lex.line_no = lno
			err = lex.mkerror("end of file in raw string")
			goto LEX_ERROR
		}
		return STRING
	}

	return int(c)

LEX_ERROR:
	lex.err = err
	return PARSE_ERROR
}

func (lex *yyLexState) mkerror(format string, args ...interface{}) error {

	return errors.New(fmt.Sprintf("%s, near line %d",
		fmt.Sprintf(format, args...),
		lex.line_no,
	))
}

func (lex *yyLexState) error(format string, args ...interface{}) {

	lex.Error(fmt.Sprintf(format, args...))
}

func (lex *yyLexState) Error(msg string) {

	if lex.err == nil { //  only report first error
		lex.err = lex.mkerror("%s", msg)
	}
}

func parse(in io.RuneReader) (*ast, error) {

	lex := &yyLexState{
		in:          in,
		line_no:     1,
		name2ast:    make(map[string]*ast),
		run_cmd2ast: make(map[*command]*ast),
		ast_root: &ast{
			yy_tok:  FLOW,
			line_no: 1,
		},
	}
	yyParse(lex)
	return lex.ast_root, lex.err
}

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 68,
	42, 7,
	49, 7,
	-2, 50,
}

const yyPrivate = 57344

const yyLast = 128

var yyAct = [...]int8{
	21, 84, 86, 73, 64, 19, 62, 10, 24, 25,
	51, 56, 22, 58, 34, 35, 20, 37, 38, 39,
	40, 41, 42, 43, 44, 76, 32, 45, 46, 23,
	11, 67, 75, 78, 55, 65, 66, 67, 79, 80,
	17, 65, 66, 24, 25, 50, 90, 22, 91, 24,
	25, 16, 68, 15, 63, 77, 18, 69, 70, 71,
	59, 60, 54, 53, 23, 85, 34, 35, 52, 37,
	38, 39, 40, 41, 42, 43, 44, 68, 33, 63,
	49, 87, 82, 81, 48, 7, 87, 89, 8, 47,
	12, 87, 92, 37, 38, 39, 40, 41, 42, 43,
	44, 67, 14, 74, 29, 65, 66, 3, 13, 27,
	9, 2, 5, 24, 25, 28, 26, 30, 31, 4,
	6, 61, 88, 83, 57, 72, 36, 1,
}

var yyPact = [...]int16{
	74, -1000, 74, -43, -1000, -11, 28, 43, -1000, -45,
	-1000, -19, 91, 91, 91, -1000, 5, -1000, -1000, -1000,
	37, -1000, -19, -19, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 23, -38, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -15, -33, -33, -33,
	-1000, 16, -19, -19, -19, -1000, -1000, -1000, 91, -1000,
	-1000, -17, -1000, -1000, 37, -1000, -1000, 35, -1000, 61,
	61, 37, -9, -1000, -6, -1000, 16, -1000, 91, -1000,
	22, -1000, -1000, -1000, -1000, 86, -1000, -1000, 4, -1000,
	86, -1000, -1000,
}

var yyPgo = [...]int8{
	0, 103, 127, 126, 0, 2, 4, 3, 125, 124,
	123, 1, 122, 6, 121, 120, 11, 119, 112, 107,
	111, 108, 102, 90, 89, 84, 80, 78, 68, 63,
	62,
}

var yyR1 = [...]int8{
	0, 2, 4, 4, 5, 5, 5, 5, 11, 12,
	12, 12, 10, 10, 7, 8, 8, 8, 9, 15,
	21, 22, 23, 1, 1, 1, 16, 16, 24, 17,
	25, 17, 26, 17, 27, 18, 19, 19, 19, 20,
	20, 20, 3, 3, 3, 3, 3, 3, 3, 3,
	6, 6, 6, 28, 6, 29, 6, 30, 6, 13,
	13, 14, 14, 14,
}

var yyR2 = [...]int8{
	0, 1, 1, 1, 1, 1, 2, 1, 1, 0,
	1, 3, 1, 3, 3, 0, 1, 3, 3, 1,
	3, 1, 1, 1, 1, 1, 0, 1, 0, 5,
	0, 5, 0, 5, 0, 6, 1, 1, 3, 0,
	2, 3, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 2, 3, 0, 4, 0, 4, 0, 4, 1,
	1, 0, 1, 3,
}

var yyChk = [...]int16{
	-1000, -2, -20, -19, -17, -18, -15, 11, 14, -19,
	50, 41, -23, -21, -22, 25, 23, 12, 13, 50,
	-6, -4, 31, 48, 27, 28, -1, 18, 24, 13,
	-1, -1, 21, -27, 29, 30, -3, 32, 33, 34,
	35, 36, 37, 38, 39, -6, -6, -24, -25, -26,
	22, 48, -28, -29, -30, 49, -16, -9, 46, -16,
	-16, -14, -13, -5, -6, 19, 20, 15, -4, -6,
	-6, -6, -8, -7, -1, 49, 42, 20, 42, 47,
	45, -13, -7, -10, -11, 43, -5, -4, -12, -11,
	42, 44, -11,
}

var yyDef = [...]int8{
	39, -2, 1, 0, 36, 37, 0, 0, 19, 0,
	40, 0, 0, 0, 0, 22, 0, 21, 34, 41,
	38, 50, 0, 0, 2, 3, 28, 23, 24, 25,
	30, 32, 0, 0, 53, 55, 57, 42, 43, 44,
	45, 46, 47, 48, 49, 51, 0, 26, 26, 26,
	20, 61, 0, 0, 0, 52, 29, 27, 15, 31,
	33, 0, 62, 59, 60, 4, 5, 0, -2, 54,
	56, 58, 0, 16, 0, 35, 0, 6, 0, 18,
	0, 63, 17, 14, 12, 9, 8, 7, 0, 10,
	0, 13, 11,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	48, 49, 3, 3, 42, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 45, 50,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 43, 3, 44, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 46, 3, 47,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:86
		{
			lex := yylex.(*yyLexState)

			yyDollar[1].ast.parent = lex.ast_root
			lex.ast_root.left = yyDollar[1].ast
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:96
		{
			yyVAL.ast = &ast{
				yy_tok:  yy_TRUE,
				line_no: yylex.(*yyLexState).line_no,
			}
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:104
		{
			yyVAL.ast = &ast{
				yy_tok:  yy_FALSE,
				line_no: yylex.(*yyLexState).line_no,
			}
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:114
		{
			yyVAL.ast = &ast{
				yy_tok:  UINT64,
				uint64:  yyDollar[1].uint64,
				line_no: yylex.(*yyLexState).line_no,
			}
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:123
		{
			yyVAL.ast = &ast{
				yy_tok:  STRING,
				string:  yyDollar[1].string,
				line_no: yylex.(*yyLexState).line_no,
			}
		}
	case 6:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:132
		{
			yyVAL.ast = &ast{
				yy_tok:  STRING,
				string:  os.ExpandEnv(yyDollar[2].string),
				line_no: yylex.(*yyLexState).line_no,
			}
		}
	case 9:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:149
		{
			yyVAL.ast = &ast{
				yy_tok:    ATT_ARRAY,
				line_no:   yylex.(*yyLexState).line_no,
				array_ref: make([]string, 0),
			}
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:158
		{
			lex := yylex.(*yyLexState)

			if yyDollar[1].ast.yy_tok != STRING {
				lex.error("attribute array element not string")
				return 0
			}
			ar := make([]string, 1)
			ar[0] = yyDollar[1].ast.string
			yyVAL.ast = &ast{
				yy_tok:    ATT_ARRAY,
				line_no:   lex.line_no,
				array_ref: ar,
			}
		}
	case 11:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:175
		{
			lex := yylex.(*yyLexState)

			if yyDollar[3].ast.yy_tok != STRING {
				lex.error("attribute array element not string")
				return 0
			}

			ar := yyDollar[1].ast.array_ref
			ar = append(ar, yyDollar[3].ast.string)
			yyDollar[1].ast.array_ref = ar
			if len(ar) > 127 {
				lex.error("attribute array > 127 elements")
				return 0
			}
			yyVAL.ast = yyDollar[1].ast
		}
	case 13:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:198
		{
			yyVAL.ast = yyDollar[2].ast
		}
	case 14:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:205
		{
			lex := yylex.(*yyLexState)

			a := &ast{
				yy_tok:  ATT,
				line_no: lex.line_no,
			}
			a.left = &ast{
				parent: a,
				yy_tok: NAME,
				string: yyDollar[1].string,
			}

			a.right = yyDollar[3].ast
			if a.right.yy_tok == STRING {
				c := len(a.right.string)
				format := a.left.string + ": string attribute: %s"
				if c == 0 {
					lex.error(format, "is empty")
					return 0
				}
				if c > 127 {
					lex.error(format, fmt.Sprintf("%d > 127", c))
					return 0
				}
			}
			yyDollar[3].ast.parent = a

			yyVAL.ast = a
		}
	case 15:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:239
		{
			yyVAL.ast = &ast{
				yy_tok:  ATT_TUPLE,
				line_no: yylex.(*yyLexState).line_no,
			}
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:247
		{
			lex := yylex.(*yyLexState)

			al := &ast{
				yy_tok:  ATT_TUPLE,
				line_no: lex.line_no,
			}
			al.left = yyDollar[1].ast
			yyDollar[1].ast.parent = al

			yyVAL.ast = al
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:261
		{
			al := yyDollar[1].ast
			a := yyDollar[3].ast
			a.parent = al

			var an *ast
			for an = al.left; an.next != nil; an = an.next {
			}
			an.next = a
			a.previous = a

			yyVAL.ast = yyDollar[1].ast
		}
	case 18:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:278
		{
			yyVAL.ast = yyDollar[2].ast
		}
	case 19:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:285
		{
			lex := yylex.(*yyLexState)
			yyVAL.ast = &ast{
				yy_tok:  CREATE,
				line_no: lex.line_no,
			}
		}
	case 20:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:296
		{
			lex := yylex.(*yyLexState)
			yyVAL.ast = &ast{
				yy_tok:  SCANNER_REF,
				line_no: lex.line_no,
				scanner_ref: &scanner{
					split: bufio.ScanLines,
				},
			}
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:310
		{
			lex := yylex.(*yyLexState)
			yyVAL.ast = &ast{
				yy_tok:      COMMAND_REF,
				line_no:     lex.line_no,
				command_ref: &command{},
			}
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:321
		{
			lex := yylex.(*yyLexState)
			yyVAL.ast = &ast{
				yy_tok:     TRACER_REF,
				line_no:    lex.line_no,
				tracer_ref: &tracer{},
			}
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:332
		{
			lex := yylex.(*yyLexState)

			yyVAL.string = lex.name
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:339
		{
			lex := yylex.(*yyLexState)

			lex.error("name exists as scanner: %s", lex.name)
			return 0
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:347
		{
			lex := yylex.(*yyLexState)

			lex.error("name exists as command: %s", lex.name)
			return 0
		}
	case 26:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:357
		{
			yyVAL.ast = &ast{
				yy_tok:  ATT_TUPLE,
				line_no: yylex.(*yyLexState).line_no,
			}
		}
	case 28:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:369
		{
			//  Note:  could production "new_name" set "name_is_name"?
			yylex.(*yyLexState).name_is_name = true

		}
	case 29:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.y:373
		{

			lex := yylex.(*yyLexState)

			lex.name_is_name = false
			lex.name2ast[yyDollar[3].string] = yyDollar[2].ast

			al := yyDollar[5].ast
			atra := yyDollar[2].ast
			al.parent = yyDollar[2].ast
			atra.left = al

			atra.tracer_ref.name = yyDollar[3].string
			atra.parent = yyDollar[1].ast

			yyDollar[1].ast.left = yyDollar[2].ast

			//  frisk the attibutes of command

			tra := atra.tracer_ref
			e := tra.frisk_att(al)
			if e != "" {
				lex.error("tracer: %s: %s", tra.name, e)
				return 0
			}

			yyVAL.ast = yyDollar[1].ast
		}
	case 30:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:403
		{
			//  Note:  could production "new_name" set "name_is_name"?
			yylex.(*yyLexState).name_is_name = true

		}
	case 31:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.y:407
		{

			lex := yylex.(*yyLexState)

			lex.name_is_name = false
			lex.name2ast[yyDollar[3].string] = yyDollar[2].ast

			al := yyDollar[5].ast
			ascan := yyDollar[2].ast
			al.parent = yyDollar[2].ast
			ascan.left = al

			ascan.scanner_ref.name = yyDollar[3].string
			ascan.parent = yyDollar[1].ast

			yyDollar[1].ast.left = yyDollar[2].ast

			//  frisk the attibutes of command

			scan := ascan.scanner_ref
			e := scan.frisk_att(al)
			if e != "" {
				lex.error("scanner: %s: %s", scan.name, e)
				return 0
			}

			yyVAL.ast = yyDollar[1].ast
		}
	case 32:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:437
		{
			yylex.(*yyLexState).name_is_name = true

		}
	case 33:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.y:440
		{
			lex := yylex.(*yyLexState)

			lex.name_is_name = false
			lex.name2ast[yyDollar[3].string] = yyDollar[2].ast

			al := yyDollar[5].ast
			acmd := yyDollar[2].ast
			al.parent = yyDollar[2].ast
			acmd.left = al

			acmd.command_ref.name = yyDollar[3].string
			acmd.parent = yyDollar[1].ast

			yyDollar[1].ast.left = yyDollar[2].ast

			//  frisk the attibutes of command

			cmd := acmd.command_ref
			e := cmd.frisk_att(al)
			if e != "" {
				lex.error("command: %s: %s", cmd.name, e)
				return 0
			}
			yyVAL.ast = yyDollar[1].ast
		}
	case 34:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:469
		{
			lex := yylex.(*yyLexState)
			cmd := lex.name2ast[lex.name].command_ref

			rc := lex.run_cmd2ast[cmd]
			if rc != nil {
				lex.error("command run twice: \"%s\"", cmd.name)
				return 0
			}

			yyVAL.ast = &ast{
				yy_tok:      RUN,
				line_no:     yylex.(*yyLexState).line_no,
				command_ref: cmd,
			}
		}
	case 35:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.y:484
		{
			lex := yylex.(*yyLexState)
			cmd := lex.name2ast[lex.name].command_ref

			ar := yyDollar[3].ast
			ar.left = yyDollar[5].ast
			ar.left.parent = ar

			yyVAL.ast = ar
			lex.run_cmd2ast[cmd] = ar
		}
	case 38:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:503
		{
			yyDollar[1].ast.right = yyDollar[3].ast
			yyDollar[3].ast.parent = yyDollar[1].ast
		}
	case 39:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:511
		{
			yyVAL.ast = &ast{
				yy_tok:  STMT,
				line_no: yylex.(*yyLexState).line_no,
			}
		}
	case 40:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:519
		{
			lex := yylex.(*yyLexState)

			a := &ast{
				yy_tok:  STMT,
				line_no: yyDollar[1].ast.line_no,
				left:    yyDollar[1].ast,
				parent:  lex.ast_root,
			}
			yyDollar[1].ast.parent = a

			yyVAL.ast = a
		}
	case 41:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:534
		{
			lex := yylex.(*yyLexState)

			s := &ast{
				yy_tok:  STMT,
				line_no: yyDollar[2].ast.line_no,
				left:    yyDollar[2].ast,
				parent:  lex.ast_root,
			}
			yyDollar[2].ast.parent = s

			//  find end statement
			sl := yyDollar[1].ast
			for ; sl.next != nil; sl = sl.next {
			}
			sl.next = s
			s.previous = sl

			yyVAL.ast = yyDollar[1].ast
		}
	case 42:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:557
		{
			yyVAL.int = EQ
		}
	case 43:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:562
		{
			yyVAL.int = NEQ
		}
	case 44:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:567
		{
			yyVAL.int = GT
		}
	case 45:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:572
		{
			yyVAL.int = GTE
		}
	case 46:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:577
		{
			yyVAL.int = LT
		}
	case 47:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:582
		{
			yyVAL.int = LTE
		}
	case 48:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:587
		{
			yyVAL.int = MATCH
		}
	case 49:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:592
		{
			yyVAL.int = NO_MATCH
		}
	case 51:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:601
		{
			yyVAL.ast = &ast{
				yy_tok:  NOT,
				left:    yyDollar[2].ast,
				line_no: yylex.(*yyLexState).line_no,
			}
			yyDollar[2].ast.parent = yyVAL.ast
		}
	case 52:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:611
		{
			yyVAL.ast = yyDollar[2].ast
		}
	case 53:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:615
		{
			yyVAL.ast = &ast{
				yy_tok:  yy_AND,
				line_no: yylex.(*yyLexState).line_no,
			}
		}
	case 54:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:620
		{
			qa := yyDollar[3].ast
			qa.left = yyDollar[1].ast
			qa.right = yyDollar[4].ast

			qa.left.parent = qa
			qa.right.parent = qa

			yyVAL.ast = qa
		}
	case 55:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:631
		{
			yyVAL.ast = &ast{
				yy_tok:  yy_OR,
				line_no: yylex.(*yyLexState).line_no,
			}
		}
	case 56:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:636
		{
			qo := yyDollar[3].ast
			qo.left = yyDollar[1].ast
			qo.right = yyDollar[4].ast

			qo.left.parent = qo
			qo.right.parent = qo

			yyVAL.ast = qo
		}
	case 57:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:647
		{
			yyVAL.ast = &ast{
				yy_tok:  yyDollar[2].int,
				line_no: yylex.(*yyLexState).line_no,
			}
		}
	case 58:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:652
		{

			bop := yyDollar[3].ast

			bop.left = yyDollar[1].ast
			bop.left.parent = bop

			bop.right = yyDollar[4].ast
			bop.right.parent = bop

			yyVAL.ast = bop
		}
	case 61:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:674
		{
			yyVAL.ast = &ast{
				yy_tok:  ARG_LIST,
				line_no: yylex.(*yyLexState).line_no,
			}
		}
	case 62:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:682
		{
			lex := yylex.(*yyLexState)

			al := &ast{
				yy_tok:  ARG_LIST,
				line_no: lex.line_no,
			}
			al.left = yyDollar[1].ast
			yyDollar[1].ast.parent = al

			yyVAL.ast = al
		}
	case 63:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:696
		{
			al := yyDollar[1].ast
			e := yyDollar[3].ast
			e.parent = al

			//  find the tail of arg list
			var an *ast
			for an = al.left; an.next != nil; an = an.next {
			}
			an.next = e
			e.previous = an

			yyVAL.ast = yyDollar[1].ast
		}
	}
	goto yystack /* stack new state and value */
}
