// Code generated by goyacc -o parser.go parser.y. DO NOT EDIT.

//line parser.y:7
package main

import __yyfmt__ "fmt"

//line parser.y:7

import (
	"bufio"
	"errors"
	"fmt"
	"io"
	"os"
	"strconv"
	"unicode"
)

const max_name_rune_count = 127

func init() {

	if yyToknames[3] != "__MIN_YYTOK" {
		panic("yyToknames[3] != __MIN_YYTOK: correct yacc command?")
	}
	//yyDebug = 4
}

//line parser.y:30
type yySymType struct {
	yys    int
	ast    *ast
	string string
	uint64 uint64
}

const __MIN_YYTOK = 57346
const ATT = 57347
const ATT_LIST = 57348
const ATT_ARRAY = 57349
const COMMAND = 57350
const COMMAND_REF = 57351
const CREATE = 57352
const EXPAND_ENV = 57353
const FLOW = 57354
const STATEMENT = 57355
const NAME = 57356
const UINT64 = 57357
const STRING = 57358
const OF = 57359
const LINES = 57360
const PARSE_ERROR = 57361
const SCANNER = 57362
const SCANNER_REF = 57363
const TRACER = 57364
const TRACER_REF = 57365

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"__MIN_YYTOK",
	"ATT",
	"ATT_LIST",
	"ATT_ARRAY",
	"COMMAND",
	"COMMAND_REF",
	"CREATE",
	"EXPAND_ENV",
	"FLOW",
	"STATEMENT",
	"NAME",
	"UINT64",
	"STRING",
	"OF",
	"LINES",
	"PARSE_ERROR",
	"SCANNER",
	"SCANNER_REF",
	"TRACER",
	"TRACER_REF",
	"','",
	"'['",
	"']'",
	"':'",
	"'('",
	"')'",
	"';'",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line parser.y:464

var keyword = map[string]int{
	"ExpandEnv": EXPAND_ENV,
	"Command":   COMMAND,
	"create":    CREATE,
	"lines":     LINES,
	"of":        OF,
	"Scanner":   SCANNER,
	"Tracer":    TRACER,
}

type yyLexState struct {
	in      io.RuneReader //  source stream
	line_no int           //  lexical line number
	eof     bool          //  seen eof in token stream
	peek    rune          //  lookahead in lexer
	err     error

	ast_root *ast
	name     string
	string
	uint64

	name2ast     map[string]*ast
	name_is_name bool
}

func (lex *yyLexState) put_name(name string, a *ast) {

	//  cheap sanity test
	if lex.name2ast[name] != nil {
		panic(fmt.Sprintf("put_name: overriding name2ast: %s", name))
	}
	if a.line_no == 0 {
		a.line_no = lex.line_no
	}
	lex.name2ast[name] = a
}

func (lex *yyLexState) pushback(c rune) {

	if lex.peek != 0 {
		panic("pushback(): push before peek") /* impossible */
	}
	lex.peek = c
	if c == '\n' {
		lex.line_no--
	}
}

/*
 *  Read next UTF8 rune.
 */
func (lex *yyLexState) get() (c rune, eof bool, err error) {

	if lex.eof {
		return 0, true, nil
	}
	if lex.peek != 0 { /* returned stashed char */
		c = lex.peek
		/*
		 *  Only pushback 1 char.
		 */
		lex.peek = 0
		if c == '\n' {
			lex.line_no++
		}
		return c, false, nil
	}
	c, _, err = lex.in.ReadRune()
	if err != nil {
		if err == io.EOF {
			lex.eof = true
			return 0, true, nil
		}
		return 0, false, err
	}

	if c == unicode.ReplacementChar {
		return 0, false, lex.mkerror("get: invalid unicode sequence")
	}
	if c == '\n' {
		lex.line_no++
	}
	return c, false, nil
}

func lookahead(lex *yyLexState, peek rune, ifyes int, ifno int) (int, error) {

	next, eof, err := lex.get()
	if err != nil {
		return 0, err
	}
	if next == peek {
		return ifyes, err
	}
	if !eof {
		lex.pushback(next)
	}
	return ifno, nil
}

/*
 *  Skip '#' comment.
 *  The scan stops on the terminating newline or error
 */
func skip_comment(lex *yyLexState) (err error) {
	var c rune
	var eof bool

	/*
	 *  Scan for newline, end of file, or error.
	 */
	for c, eof, err = lex.get(); !eof && err == nil; c, eof, err = lex.get() {
		if c == '\n' {
			return
		}
	}
	return err

}

// skip over whitespace in code, complicated by # coments.

func skip_space(lex *yyLexState) (c rune, eof bool, err error) {

	for c, eof, err = lex.get(); !eof && err == nil; c, eof, err = lex.get() {
		if unicode.IsSpace(c) {
			continue
		}
		if c != '#' {
			return c, false, nil
		}

		/*
		 *  Skipping over # comment terminated by newline or EOF
		 */
		err = skip_comment(lex)
		if err != nil {
			return 0, false, err
		}
	}
	return 0, eof, err
}

/*
 *  Very simple utf8 string scanning, with no proper escapes for characters.
 *  Expect this module to be replaced with correct text.Scanner.
 */
func (lex *yyLexState) scanner_string(yylval *yySymType) (eof bool, err error) {
	var c rune
	s := ""

	for c, eof, err = lex.get(); !eof && err == nil; c, eof, err = lex.get() {
		if c == '"' {
			yylval.string = s
			return false, nil
		}
		switch c {
		case '\n':
			return false, lex.mkerror("new line in string")
		case '\r':
			return false, lex.mkerror("carriage return in string")
		case '\t':
			return false, lex.mkerror("tab in string")
		case '\\':
			return false, lex.mkerror("backslash in string")
		}
		s += string(c)
	}
	if err != nil {
		return false, err
	}
	return true, nil
}

/*
 *  Scan an almost raw `...`  string as defined in golang.
 *  Carriage return is stripped.
 */
func (lex *yyLexState) scanner_raw_string(yylval *yySymType) (eof bool, err error) {
	var c rune
	s := ""

	/*
	 *  Scan a raw string of unicode letters, accepting all but `
	 */
	for c, eof, err = lex.get(); !eof && err == nil; c, eof, err = lex.get() {

		switch c {
		case '\r':
			//  why does go skip carriage return?  raw is not so raw
			continue
		case '`':
			yylval.string = s
			return false, nil
		}
		s += string(c)
	}
	if err != nil {
		return false, err
	}
	return true, nil
}

/*
 *  Scan a word consisting of a sequence of unicode Letters, Numbers and '_'
 *  characters.
 */
func (lex *yyLexState) scanner_word(yylval *yySymType, c rune) (tok int, err error) {
	var eof bool

	w := string(c) //  panic() if cast fails?
	count := 1

	/*
	 *  Scan a string of unicode (?) letters, numbers/digits and '_'
	 *  characters.
	 */
	for c, eof, err = lex.get(); !eof && err == nil; c, eof, err = lex.get() {
		if c > 127 ||
			(c != '_' &&
				!unicode.IsLetter(c) &&
				!unicode.IsNumber(c)) {
			break
		}
		count++
		if count > max_name_rune_count {
			return 0, lex.mkerror("word: too many chars: max=%d",
				max_name_rune_count)
		}
		w += string(c) //  Note: replace with string builder?
	}
	if err != nil {
		return 0, err
	}
	if !eof {
		lex.pushback(c) /* first character after word */
	}

	if keyword[w] > 0 { /* got a keyword */
		return keyword[w], nil /* return yacc generated token */
	}

	lex.name = w
	if lex.name_is_name == false && lex.name2ast[w] != nil {
		return lex.name2ast[w].yy_tok, nil
	}
	return NAME, nil
}

func (lex *yyLexState) scanner_uint64(yylval *yySymType, c rune) (err error) {
	var eof bool

	ui64 := string(c)
	count := 1

	/*
	 *  Scan a string of unicode numbers/digits and let Scanf parse the
	 *  actual digit string.
	 */
	for c, eof, err = lex.get(); !eof && err == nil; c, eof, err = lex.get() {
		count++
		if count > 20 {
			return lex.mkerror("uint64 > 20 digits")
		}
		if c > 127 || !unicode.IsNumber(c) {
			break
		}
		ui64 += string(c)
	}
	if err != nil {
		return
	}
	if !eof {
		lex.pushback(c) //  first character after ui64
	}

	yylval.uint64, err = strconv.ParseUint(ui64, 10, 64)
	return
}

//  lexical scan of a token

func (lex *yyLexState) Lex(yylval *yySymType) (tok int) {

	if lex.err != nil {
		return PARSE_ERROR
	}
	if lex.eof {
		return 0
	}
	c, eof, err := skip_space(lex)
	if err != nil {
		goto PARSE_ERROR
	}
	if eof {
		return 0
	}

	switch {

	//  ascii outside of strings, for time being (why?)
	case c > 127:
		goto PARSE_ERROR

	case unicode.IsLetter(c) || c == '_':
		tok, err = lex.scanner_word(yylval, c)
		if err != nil {
			goto PARSE_ERROR
		}
		return tok

	case unicode.IsNumber(c):
		err = lex.scanner_uint64(yylval, c)
		if err != nil {
			goto PARSE_ERROR
		}
		return UINT64

	case c == '"':
		lno := lex.line_no // reset line number on error

		eof, err = lex.scanner_string(yylval)
		if err != nil {
			goto PARSE_ERROR
		}
		if eof {
			lex.line_no = lno
			err = lex.mkerror("unexpected end of file in string")
			goto PARSE_ERROR
		}
		return STRING

	case c == '`':
		lno := lex.line_no // reset line number on error

		eof, err = lex.scanner_raw_string(yylval)
		if err != nil {
			goto PARSE_ERROR
		}
		if eof {
			lex.line_no = lno
			err = lex.mkerror("unexpected end of file in raw string")
			goto PARSE_ERROR
		}
		return STRING
	}
	return int(c)

PARSE_ERROR:
	lex.err = err
	return PARSE_ERROR
}

func (lex *yyLexState) mkerror(format string, args ...interface{}) error {

	return errors.New(fmt.Sprintf("%s, near line %d",
		fmt.Sprintf(format, args...),
		lex.line_no,
	))
}

func (lex *yyLexState) error(format string, args ...interface{}) {

	lex.Error(fmt.Sprintf(format, args...))
}

func (lex *yyLexState) Error(msg string) {

	if lex.err == nil { //  only report first error
		lex.err = lex.mkerror("%s", msg)
	}
}

func parse(in io.RuneReader) (*ast, error) {

	lex := &yyLexState{
		in:       in,
		line_no:  1,
		name2ast: make(map[string]*ast),
		ast_root: &ast{
			yy_tok:  FLOW,
			line_no: 1,
		},
	}
	yyParse(lex)
	return lex.ast_root, lex.err
}

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 51

var yyAct = [...]int8{
	38, 31, 33, 14, 7, 42, 35, 34, 27, 40,
	41, 46, 26, 47, 13, 25, 42, 18, 21, 39,
	40, 41, 16, 45, 5, 24, 12, 3, 11, 17,
	6, 23, 32, 22, 8, 36, 28, 29, 10, 9,
	44, 15, 19, 20, 4, 2, 43, 48, 37, 30,
	1,
}

var yyPact = [...]int16{
	14, -1000, 14, -26, 6, -1000, -27, -1000, 8, 8,
	8, -1000, 1, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -3, -20, -20, -20, -1000, -1000, 8, -1000, -1000,
	-22, -1000, -21, 8, -1000, -6, -1000, -1000, -1000, 5,
	-1000, -1000, 7, -13, -1000, -1000, 5, -1000, -1000,
}

var yyPgo = [...]int8{
	0, 32, 50, 1, 49, 12, 48, 0, 46, 27,
	45, 44, 39, 38, 34, 33, 31, 25,
}

var yyR1 = [...]int8{
	0, 2, 7, 7, 7, 8, 8, 8, 6, 6,
	3, 4, 4, 4, 5, 5, 11, 12, 13, 14,
	1, 1, 1, 15, 9, 16, 9, 17, 9, 10,
	10, 10,
}

var yyR2 = [...]int8{
	0, 1, 1, 1, 2, 0, 1, 3, 1, 3,
	3, 0, 1, 3, 0, 3, 1, 3, 1, 1,
	1, 1, 1, 0, 5, 0, 5, 0, 5, 0,
	2, 3,
}

var yyChk = [...]int16{
	-1000, -2, -10, -9, -11, 10, -9, 30, -14, -12,
	-13, 22, 20, 8, 30, -1, 14, 21, 9, -1,
	-1, 17, -15, -16, -17, 18, -5, 28, -5, -5,
	-4, -3, -1, 24, 29, 27, -3, -6, -7, 25,
	15, 16, 11, -8, -7, 16, 24, 26, -7,
}

var yyDef = [...]int8{
	29, -2, 1, 0, 0, 16, 0, 30, 0, 0,
	0, 19, 0, 18, 31, 23, 20, 21, 22, 25,
	27, 0, 14, 14, 14, 17, 24, 11, 26, 28,
	0, 12, 0, 0, 15, 0, 13, 10, 8, 5,
	2, 3, 0, 0, 6, 4, 0, 9, 7,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	28, 29, 3, 3, 24, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 27, 30,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 25, 3, 26,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:63
		{
			lex := yylex.(*yyLexState)

			yyDollar[1].ast.parent = lex.ast_root
			lex.ast_root.left = yyDollar[1].ast
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:73
		{
			yyVAL.ast = &ast{
				yy_tok:  UINT64,
				uint64:  yyDollar[1].uint64,
				line_no: yylex.(*yyLexState).line_no,
			}
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:82
		{
			yyVAL.ast = &ast{
				yy_tok:  STRING,
				string:  yyDollar[1].string,
				line_no: yylex.(*yyLexState).line_no,
			}
		}
	case 4:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:91
		{
			yyVAL.ast = &ast{
				yy_tok:  STRING,
				string:  os.ExpandEnv(yyDollar[2].string),
				line_no: yylex.(*yyLexState).line_no,
			}
		}
	case 5:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:102
		{
			yyVAL.ast = &ast{
				yy_tok:    ATT_ARRAY,
				line_no:   yylex.(*yyLexState).line_no,
				array_ref: make([]string, 0),
			}
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:111
		{
			lex := yylex.(*yyLexState)

			if yyDollar[1].ast.yy_tok != STRING {
				lex.error("attribute array element not string")
				return 0
			}
			ar := make([]string, 1)
			ar[0] = yyDollar[1].ast.string
			yyVAL.ast = &ast{
				yy_tok:    ATT_ARRAY,
				line_no:   lex.line_no,
				array_ref: ar,
			}
		}
	case 7:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:128
		{
			lex := yylex.(*yyLexState)

			if yyDollar[3].ast.yy_tok != STRING {
				lex.error("attribute array element not string")
				return 0
			}

			ar := yyDollar[1].ast.array_ref
			ar = append(ar, yyDollar[3].ast.string)
			yyDollar[1].ast.array_ref = ar
			if len(ar) > 127 {
				lex.error("attribute array > 127 elements")
				return 0
			}
			yyVAL.ast = yyDollar[1].ast
		}
	case 9:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:151
		{
			yyVAL.ast = yyDollar[2].ast
		}
	case 10:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:158
		{
			lex := yylex.(*yyLexState)

			a := &ast{
				yy_tok:  ATT,
				line_no: lex.line_no,
			}
			a.left = &ast{
				parent: a,
				yy_tok: NAME,
				string: yyDollar[1].string,
			}

			a.right = yyDollar[3].ast
			if a.right.yy_tok == STRING {
				c := len(a.right.string)
				format := a.left.string + ": string attribute: %s"
				if c == 0 {
					lex.error(format, "is empty")
					return 0
				}
				if c > 127 {
					lex.error(format, fmt.Sprintf("%d > 127", c))
					return 0
				}
			}
			yyDollar[3].ast.parent = a

			yyVAL.ast = a
		}
	case 11:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:192
		{
			yyVAL.ast = &ast{
				yy_tok:  ATT_LIST,
				line_no: yylex.(*yyLexState).line_no,
			}
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:200
		{
			lex := yylex.(*yyLexState)

			al := &ast{
				yy_tok:  ATT_LIST,
				line_no: lex.line_no,
			}
			al.left = yyDollar[1].ast
			yyDollar[1].ast.parent = al

			yyVAL.ast = al
		}
	case 13:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:214
		{
			al := yyDollar[1].ast
			a := yyDollar[3].ast
			a.parent = al

			var an *ast
			for an = al.left; an.next != nil; an = an.next {
			}
			an.next = a
			a.previous = a

			yyVAL.ast = yyDollar[1].ast
		}
	case 14:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:231
		{
			yyVAL.ast = &ast{
				yy_tok:  ATT_LIST,
				line_no: yylex.(*yyLexState).line_no,
			}
		}
	case 15:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:239
		{
			yyVAL.ast = yyDollar[2].ast
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:246
		{
			lex := yylex.(*yyLexState)
			yyVAL.ast = &ast{
				yy_tok:  CREATE,
				line_no: lex.line_no,
			}
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:257
		{
			lex := yylex.(*yyLexState)
			yyVAL.ast = &ast{
				yy_tok:  SCANNER_REF,
				line_no: lex.line_no,
				scanner_ref: &scanner{
					split: bufio.ScanLines,
				},
			}
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:271
		{
			lex := yylex.(*yyLexState)
			yyVAL.ast = &ast{
				yy_tok:      COMMAND_REF,
				line_no:     lex.line_no,
				command_ref: &command{},
			}
		}
	case 19:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:282
		{
			lex := yylex.(*yyLexState)
			yyVAL.ast = &ast{
				yy_tok:     TRACER_REF,
				line_no:    lex.line_no,
				tracer_ref: &tracer{},
			}
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:293
		{
			lex := yylex.(*yyLexState)

			yyVAL.string = lex.name
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:300
		{
			lex := yylex.(*yyLexState)

			e := fmt.Sprintf("scanner: name already exists: %s", lex.name)
			lex.Error(e)
			return 0
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:309
		{
			lex := yylex.(*yyLexState)

			e := fmt.Sprintf("command: name already exists: %s", lex.name)
			lex.Error(e)
			return 0
		}
	case 23:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:319
		{
			//  Note:  could production "new_name" set "name_is_name"?
			yylex.(*yyLexState).name_is_name = true

		}
	case 24:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.y:323
		{

			lex := yylex.(*yyLexState)

			lex.name_is_name = false
			lex.put_name(yyDollar[3].string, yyDollar[2].ast)

			al := yyDollar[5].ast
			atra := yyDollar[2].ast
			al.parent = yyDollar[2].ast
			atra.left = al

			atra.tracer_ref.name = yyDollar[3].string
			atra.parent = yyDollar[1].ast

			yyDollar[1].ast.left = yyDollar[2].ast

			//  frisk the attibutes of command

			tra := atra.tracer_ref
			e := tra.frisk_att(al)
			if e != "" {
				lex.error("tracer: %s: %s", tra.name, e)
				return 0
			}

			yyVAL.ast = yyDollar[1].ast
		}
	case 25:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:353
		{
			//  Note:  could production "new_name" set "name_is_name"?
			yylex.(*yyLexState).name_is_name = true

		}
	case 26:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.y:357
		{

			lex := yylex.(*yyLexState)

			lex.name_is_name = false
			lex.put_name(yyDollar[3].string, yyDollar[2].ast)

			al := yyDollar[5].ast
			ascan := yyDollar[2].ast
			al.parent = yyDollar[2].ast
			ascan.left = al

			ascan.scanner_ref.name = yyDollar[3].string
			ascan.parent = yyDollar[1].ast

			yyDollar[1].ast.left = yyDollar[2].ast

			//  frisk the attibutes of command

			scan := ascan.scanner_ref
			e := scan.frisk_att(al)
			if e != "" {
				lex.error("scanner: %s: %s", scan.name, e)
				return 0
			}

			yyVAL.ast = yyDollar[1].ast
		}
	case 27:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:387
		{
			yylex.(*yyLexState).name_is_name = true

		}
	case 28:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.y:390
		{
			lex := yylex.(*yyLexState)

			lex.name_is_name = false
			lex.put_name(yyDollar[3].string, yyDollar[2].ast)

			al := yyDollar[5].ast
			acmd := yyDollar[2].ast
			al.parent = yyDollar[2].ast
			acmd.left = al

			acmd.command_ref.name = yyDollar[3].string
			acmd.parent = yyDollar[1].ast

			yyDollar[1].ast.left = yyDollar[2].ast

			//  frisk the attibutes of command

			cmd := acmd.command_ref
			e := cmd.frisk_att(al)
			if e != "" {
				lex.error("command: %s: %s", cmd.name, e)
				return 0
			}

			yyVAL.ast = yyDollar[1].ast
		}
	case 29:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:421
		{
			yyVAL.ast = &ast{
				yy_tok:  STATEMENT,
				line_no: yylex.(*yyLexState).line_no,
			}
		}
	case 30:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:429
		{
			lex := yylex.(*yyLexState)

			a := &ast{
				yy_tok:  STATEMENT,
				line_no: yyDollar[1].ast.line_no,
				left:    yyDollar[1].ast,
				parent:  lex.ast_root,
			}
			yyDollar[1].ast.parent = a

			yyVAL.ast = a
		}
	case 31:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:444
		{
			lex := yylex.(*yyLexState)

			s := &ast{
				yy_tok:  STATEMENT,
				line_no: yyDollar[2].ast.line_no,
				left:    yyDollar[2].ast,
				parent:  lex.ast_root,
			}
			yyDollar[2].ast.parent = s

			//  find end statement
			sl := yyDollar[1].ast
			for ; sl.next != nil; sl = sl.next {
			}
			sl.next = s
			s.previous = sl

			yyVAL.ast = yyDollar[1].ast
		}
	}
	goto yystack /* stack new state and value */
}
