#!/bin/bash
#
#  Synopsis:
#	Pull yesterday's edgar reports from www.sec.gov/Archives/edgar/Feed
#  Usage:
#	#
#	#  successfully pulled files pushed from $SECEDGAR_ROOT/tmp to
#	#  $SECEDGAR_ROOT/spool
#	#
#	export SECEDGAR_ROOT=$HOME/opt/jmscott
#
#	#
#	#  script needs gnu date for calculating 'yesterday', so, on macports,
#	#  add gnuutils path, or where ever 'date' lives.
#	#
#	PATH=/opt/local/libexec/gnubin:$PATH
#
#	LOG=$SECEDGAR_ROOT/log/edgar-pull-daily-$(date +%a).log
#	13 2 * * Tue-Sat edgar-pull-daily >>$LOG 2>&1
#  Note:
#	Rename the script edgar-wget-daily.
#
#	For missing files on edgar, wget sees the confusing http error
#
#		ERROR 403: Forbidden.
#
#	instead of 404: Not found.  this could confuse a stupid person.
#
#	Depends on GNU data to calcuate 'yesterday'.
#

START_EPOCH=$(date +%a)
FEED_URL=https://www.sec.gov/Archives/edgar/Feed/

now()
{
	date +'%Y/%m/%d %H:%M:%S'
}

log()
{
	echo "$(now): $@"
}

die()
{
	MSG="ERROR: $@"
	RUN=$SECEDGAR_ROOT/run
	test -w "$RUN" && echo "$(now): $MSG" >>$RUN/$(basename $0).fault
	log "$MSG" >&2
	exit 1
}

get_quarter()
{
	MONTH=$1
	case $MONTH in
	01|02|03)
		QUARTER=1
		;;
	04|05|06)
		QUARTER=2
		;;
	07|08|09)
		QUARTER=3
		;;
	10|11|12)
		QUARTER=4
		;;
	*)
		die "unknown month: $MONTH"
		;;
	esac
	echo $QUARTER
}

leave()
{
	STATUS=$?
	DURATION=$(duration-english $(expr $(date +%a) - $START_EPOCH))
	log "good bye, cruel world: $DURATION"
	exit $STATUS
}

test $# = 0 || die "wrong count of cli arguments: got $#, expected 0"

log 'hello, world'
trap leave EXIT

test -n "$SECEDGAR_ROOT" || die 'env var not defined: SECEDGAR_ROOT'
log "SECEDGAR_ROOT=$SECEDGAR_ROOT"
cd $SECEDGAR_ROOT || die "cd SECEDGAR_ROOT failed: exit status=$?"

PROFILE=etc/profile
log "profile: $PROFILE"
test -r $PROFILE || die "can not read etc/profile: $PROFILE"
. $PROFILE

TMPDIR=${TMPDIR:=/tmp}
log "TMPDIR=$TMPDIR"

YEAR=$(date --date=yesterday +'%Y')
test $? = 0 || die "date yester year failed: exit status=$?"
log "report year: $YEAR"

MONTH=$(date --date=yesterday +'%m')
test $? = 0 || die "date yester month failed: exit status=$?"
log "report month: $MONTH"

DAY=$(date --date=yesterday +'%d')
test $? = 0 || die "date yester day failed: exit status=$?"
log "report day: $DAY"

cd $TMPDIR || die "cd tmp failed: exit status=$?"

QTR=QTR$(get_quarter $MONTH)
log "report quarter: $QTR"

FILE=$YEAR$MONTH$DAY.nc.tar.gz
log "download file: $FILE"
test -e ../spool/$FILE && die "file exists in spool: ../spool/$FILE"

log "feed url (see for missing): $FEED_URL"
URL="$FEED_URL/$YEAR/$QTR/$FILE"
log "pull url: $URL"

log 'pulling zip from sec edgar ...'
wget --report-speed=bits --output-file - "$URL"			||
		die "wget secedgar failed: exit status=$?"
test -e $FILE || die "sec file does not exist: $FILE"
test -s $FILE || die 'sec file is empty'

log "moving zip to dir ../spool/: $FILE"
SPOOL=$SECEDGAR_ROOT/spool
log "mv zip file to spool: $SPOOL"
mv $FILE $SPOOL || die "mv spool failed: exit status=$?"
log "return to root: $SECEDGAR_ROOT"
cd $SECEDGAR_ROOT || die "return cd SECEDGAR_ROOT failed: exit status=$?"

FILE="spool/$FILE"
log "edgar-put-daily: $FILE"
TMPDIR=. edgar-put-daily $FILE || die "edgar-put-daily failed: exit status=$?"

exit 0
